# Generated by Django 4.2.8 on 2024-01-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/goods/console/')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('productn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.productn')),
                ('model_console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.modelconsole')),
            ],
            bases=('cart.productn',),
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('productn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.productn')),
                ('category', models.ManyToManyField(to='labels.categorygame')),
                ('compatibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.modelconsole')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.developer')),
            ],
            bases=('cart.productn',),
        ),
    ]
