# Generated by Django 4.2.8 on 2024-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/img_avatar.png', null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
