# Generated by Django 4.2.8 on 2024-01-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('model_console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.modelconsole')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.goods')),
            ],
            bases=('goods.goods',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/goods/console/')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goods.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.goods')),
                ('category', models.ManyToManyField(to='labels.categorygame')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.developer')),
            ],
            bases=('goods.goods',),
        ),
    ]
