# Generated by Django 4.2.8 on 2024-01-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/goods/game/')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.game')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/goods/console/')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.console')),
            ],
        ),
    ]
