# Generated by Django 4.2.8 on 2024-01-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_gallerygame_galleryconsole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
