# Generated by Django 4.2.8 on 2024-01-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_gallerygame_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AlterField(
            model_name='galleryconsole',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goods.console'),
        ),
    ]
