# Generated by Django 4.2.8 on 2024-01-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('goods', '0005_remove_console_status_remove_game_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product'),
        ),
        migrations.AddField(
            model_name='game',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product'),
        ),
    ]
